In [ ]:
import numpy as np

In [ ]:
my_list = [54 , "aud" , True , 5+5j]
my_list

[54, 'aud', True, (5+5j)]

In [ ]:
np.zeros((5,5),dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
np.ones((5,5), dtype = "int64")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.random((5,5))

array([[0.96609545, 0.25958236, 0.52093917, 0.33375829, 0.54272678],
       [0.91513179, 0.15515633, 0.81414917, 0.65227196, 0.81053718],
       [0.48879522, 0.2277924 , 0.81110169, 0.09781943, 0.38990261],
       [0.97803188, 0.81400877, 0.27354003, 0.16522079, 0.22782828],
       [0.04006799, 0.03377949, 0.662161  , 0.38884574, 0.17734822]])

In [ ]:
np.random.randint(10)

7

In [ ]:
a = np.ones((5,5))
b = np.ones((5,5))
print(a)
print()
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np.sin(a)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [ ]:
a.max(axis=1)

array([1., 1., 1., 1., 1.])

In [ ]:
a=np.random.randint(100,size=(6,5))
a

array([[62, 57, 94, 15, 83],
       [ 5, 91, 70, 63, 87],
       [59, 20, 72, 18, 63],
       [13, 36, 41,  8, 20],
       [30, 73, 84, 32, 31],
       [14, 57, 86, 96, 50]])

In [ ]:
a = np.array([[[1,2],[2,5]]])
b = np.array([[2],[8]])
print(a)
print()
print(b)

[[[1 2]
  [2 5]]]

[[2]
 [8]]


In [ ]:
a.dot(b)

array([[[18],
        [44]]])

In [ ]:
np.matmul(a,b)

array([[[18],
        [44]]])

In [ ]:
a+b

array([[ 4],
       [16]])

In [ ]:
a = np.array([[1,2],[2,5]])
np.linalg.inv(a)

array([[ 5., -2.],
       [-2.,  1.]])

In [ ]:
a = np.array([[1,2],[2,5]])
b = np.array([[2],[8]])

np.linalg.solve(a,b)

array([[-6.],
       [ 4.]])

In [ ]:
import time

list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(len(list1))]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

Python List Addition Time: 0.11229801177978516 seconds


In [ ]:
import numpy as np
import time

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
result_np_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

NumPy Array Addition Time: 0.00563359260559082 seconds


In [ ]:
start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(len(list1))]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")



Python List Multiplication Time: 0.14144396781921387 seconds


In [ ]:
start = time.time()
result_np_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")




NumPy Array Multiplication Time: 0.007898807525634766 seconds


In [ ]:
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start, "seconds")



NumPy Array Dot Product Time: 0.0030851364135742188 seconds


In [ ]:
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")


Python List Matrix Multiplication Time: 192.94765710830688 seconds
